# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Chase Podiatry & Chiropody"
slogan: "For all your footcare needs"
email: reception@chase-podiatry.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Providing specialist foot care in Cannock and Burntwood with a warm, friendly service, treating you as a person
  not just a patient.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://www.chase-podiatry.co.uk/" # the base hostname & protocol for your site, e.g. http://example.com
phone: 01543 577566
google_analytics: "UA-32318153-1"

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
#theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at
permalink: pretty

sass:
  load_paths:
    - _sass
    - node_modules

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page

# Explicitly include in processing
include:
 - _headers
 - _redirects

# Exclude from processing.
exclude:
 - Gemfile
 - Gemfile.lock
 - gulpfile.js
 - node_modules
 - package.json
 - README.md
 - vendor/
 - yarn.lock
